import { AIAgent } from './types'

export const aiAgents: AIAgent[] = [
  {
    id: 'qualification-compliance',
    name: 'AI Qualification Compliance Agent',
    description: 'Advanced AI-powered qualification verification and compliance checking for UK sponsors with red flag detection and expert-level assessment.',
    icon: 'GraduationCap',
    price: '£199.99',
    originalPrice: '£299.99',
    features: [
      'Document upload and AI analysis',
      'Expert-level qualification assessment',
      'Red flag detection for serious breaches',
      'Professional paragraph reports',
      'Care Certificate verification',
      'SOC code compliance checking',
      'Dashboard with analytics',
      'AI chat assistant',
      'Download, email, and print reports',
      'Worker management system'
    ],
    keyBenefits: [
      'Automated compliance checking',
      'Expert-level analysis quality',
      'Immediate breach detection',
      'Professional reporting',
      'Time-saving automation'
    ],
    status: 'available',
    category: 'compliance',
    complexity: 'advanced',
    href: '/ai-qualification-compliance',
    popular: true,
    new: false,
    showcaseImage: '/images/ai-qualification-showcase.png'
  },
  {
    id: 'salary-compliance',
    name: 'AI Salary Compliance Agent',
    description: 'Comprehensive salary compliance analysis with payslip verification, NMW checking, and Home Office threshold monitoring.',
    icon: 'DollarSign',
    price: '£179.99',
    originalPrice: '£249.99',
    features: [
      'Payslip analysis and verification',
      'National Minimum Wage checking',
      'Home Office threshold monitoring',
      'Monthly payment tracking',
      'Underpayment detection',
      'Professional assessment reports',
      'Salary compliance dashboard',
      'AI salary assistant',
      'Report generation and sharing',
      'Worker salary management'
    ],
    keyBenefits: [
      'Automated salary verification',
      'NMW compliance assurance',
      'Underpayment prevention',
      'Professional documentation',
      'Sponsor duty compliance'
    ],
    status: 'available',
    category: 'compliance',
    complexity: 'advanced',
    href: '/ai-salary-compliance',
    popular: false,
    new: true,
    showcaseImage: '/images/ai-salary-showcase.png'
  },
  {
    id: 'document-compliance',
    name: 'AI Document Compliance Agent',
    description: 'Intelligent document analysis and compliance checking for UK sponsor documentation requirements.',
    icon: 'FileText',
    price: '£159.99',
    originalPrice: '£229.99',
    features: [
      'Document upload and analysis',
      'Compliance requirement checking',
      'Missing document detection',
      'Format validation',
      'Professional assessment reports',
      'Document compliance dashboard',
      'AI document assistant',
      'Report generation and sharing',
      'Document management system',
      'Compliance tracking'
    ],
    keyBenefits: [
      'Automated document checking',
      'Missing document alerts',
      'Format compliance assurance',
      'Professional documentation',
      'Time-saving automation'
    ],
    status: 'available',
    category: 'compliance',
    complexity: 'basic',
    href: '/ai-document-compliance',
    popular: false,
    new: false
  },
  {
    id: 'right-to-work',
    name: 'AI Right to Work Agent',
    description: 'Automated right to work verification and compliance checking for UK employers.',
    icon: 'Shield',
    price: '£189.99',
    originalPrice: '£269.99',
    features: [
      'Right to work verification',
      'Document authenticity checking',
      'Visa status monitoring',
      'Compliance reporting',
      'Professional assessment reports',
      'Right to work dashboard',
      'AI verification assistant',
      'Report generation and sharing',
      'Worker verification management',
      'Compliance tracking'
    ],
    keyBenefits: [
      'Automated verification',
      'Document authenticity assurance',
      'Visa status monitoring',
      'Professional documentation',
      'Compliance assurance'
    ],
    status: 'coming-soon',
    category: 'compliance',
    complexity: 'advanced',
    href: '/ai-right-to-work-compliance',
    popular: false,
    new: false
  },
  {
    id: 'right-to-rent',
    name: 'AI Right to Rent Agent',
    description: 'Comprehensive right to rent verification and compliance checking for UK landlords.',
    icon: 'Building',
    price: '£169.99',
    originalPrice: '£239.99',
    features: [
      'Right to rent verification',
      'Document authenticity checking',
      'Tenant status monitoring',
      'Compliance reporting',
      'Professional assessment reports',
      'Right to rent dashboard',
      'AI verification assistant',
      'Report generation and sharing',
      'Tenant verification management',
      'Compliance tracking'
    ],
    keyBenefits: [
      'Automated verification',
      'Document authenticity assurance',
      'Tenant status monitoring',
      'Professional documentation',
      'Compliance assurance'
    ],
    status: 'coming-soon',
    category: 'compliance',
    complexity: 'advanced',
    href: '/ai-right-to-rent-compliance',
    popular: false,
    new: false
  },
  {
    id: 'skills-experience',
    name: 'AI Skills & Experience Agent',
    description: 'Advanced skills and experience assessment with AI-powered analysis and compliance checking.',
    icon: 'Users',
    price: '£209.99',
    originalPrice: '£289.99',
    features: [
      'Skills assessment and analysis',
      'Experience verification',
      'Competency evaluation',
      'Professional assessment reports',
      'Skills compliance dashboard',
      'AI assessment assistant',
      'Report generation and sharing',
      'Worker skills management',
      'Compliance tracking',
      'Expert-level analysis'
    ],
    keyBenefits: [
      'Automated skills assessment',
      'Experience verification',
      'Competency evaluation',
      'Professional documentation',
      'Expert-level analysis'
    ],
    status: 'available',
    category: 'hr',
    complexity: 'advanced',
    href: '/ai-skills-experience-compliance',
    popular: false,
    new: false
  },
  {
    id: 'contracted-hours',
    name: 'AI Contracted Hours Agent',
    description: 'Contracted hours compliance monitoring and analysis for UK sponsors.',
    icon: 'Clock',
    price: '£149.99',
    originalPrice: '£219.99',
    features: [
      'Hours tracking and monitoring',
      'Contract compliance checking',
      'Overtime analysis',
      'Professional assessment reports',
      'Hours compliance dashboard',
      'AI monitoring assistant',
      'Report generation and sharing',
      'Worker hours management',
      'Compliance tracking',
      'Automated alerts'
    ],
    keyBenefits: [
      'Automated hours monitoring',
      'Contract compliance assurance',
      'Overtime analysis',
      'Professional documentation',
      'Compliance alerts'
    ],
    status: 'coming-soon',
    category: 'hr',
    complexity: 'basic',
    href: '/ai-contracted-hours-compliance',
    popular: false,
    new: false
  },
  {
    id: 'genuine-vacancies',
    name: 'AI Genuine Vacancies Agent',
    description: 'Genuine vacancy verification and compliance checking for UK sponsors.',
    icon: 'Target',
    price: '£179.99',
    originalPrice: '£249.99',
    features: [
      'Vacancy verification',
      'Market analysis',
      'Compliance checking',
      'Professional assessment reports',
      'Vacancy compliance dashboard',
      'AI verification assistant',
      'Report generation and sharing',
      'Vacancy management',
      'Compliance tracking',
      'Market insights'
    ],
    keyBenefits: [
      'Automated vacancy verification',
      'Market analysis',
      'Compliance assurance',
      'Professional documentation',
      'Market insights'
    ],
    status: 'coming-soon',
    category: 'hr',
    complexity: 'advanced',
    href: '/ai-genuine-vacancies-compliance',
    popular: false,
    new: false
  },
  {
    id: 'recruitment-practices',
    name: 'AI Recruitment Practices Agent',
    description: 'Recruitment practices compliance monitoring and analysis for UK sponsors.',
    icon: 'Users',
    price: '£189.99',
    originalPrice: '£259.99',
    features: [
      'Recruitment practice analysis',
      'Compliance monitoring',
      'Best practice assessment',
      'Professional assessment reports',
      'Recruitment compliance dashboard',
      'AI analysis assistant',
      'Report generation and sharing',
      'Practice management',
      'Compliance tracking',
      'Best practice recommendations'
    ],
    keyBenefits: [
      'Automated practice analysis',
      'Compliance monitoring',
      'Best practice assessment',
      'Professional documentation',
      'Practice recommendations'
    ],
    status: 'coming-soon',
    category: 'hr',
    complexity: 'advanced',
    href: '/ai-recruitment-practices-compliance',
    popular: false,
    new: false
  },
  {
    id: 'reporting-duties',
    name: 'AI Reporting Duties Agent',
    description: 'Reporting duties compliance monitoring and automated reporting for UK sponsors.',
    icon: 'BarChart3',
    price: '£199.99',
    originalPrice: '£279.99',
    features: [
      'Reporting duty monitoring',
      'Automated reporting',
      'Compliance tracking',
      'Professional assessment reports',
      'Reporting compliance dashboard',
      'AI reporting assistant',
      'Report generation and sharing',
      'Duty management',
      'Compliance tracking',
      'Automated alerts'
    ],
    keyBenefits: [
      'Automated duty monitoring',
      'Automated reporting',
      'Compliance tracking',
      'Professional documentation',
      'Automated alerts'
    ],
    status: 'coming-soon',
    category: 'compliance',
    complexity: 'enterprise',
    href: '/ai-reporting-duties-compliance',
    popular: false,
    new: false
  },
  {
    id: 'record-keeping',
    name: 'AI Record Keeping Agent',
    description: 'Record keeping compliance monitoring and management for UK sponsors.',
    icon: 'FileText',
    price: '£169.99',
    originalPrice: '£239.99',
    features: [
      'Record keeping monitoring',
      'Compliance checking',
      'Document management',
      'Professional assessment reports',
      'Record keeping dashboard',
      'AI management assistant',
      'Report generation and sharing',
      'Record management',
      'Compliance tracking',
      'Automated organization'
    ],
    keyBenefits: [
      'Automated record monitoring',
      'Compliance checking',
      'Document management',
      'Professional documentation',
      'Automated organization'
    ],
    status: 'coming-soon',
    category: 'compliance',
    complexity: 'basic',
    href: '/ai-record-keeping-compliance',
    popular: false,
    new: false
  },
  {
    id: 'sponsor-compliance',
    name: 'AI Sponsor Compliance Agent',
    description: 'Comprehensive sponsor compliance monitoring and management for UK sponsors.',
    icon: 'Shield',
    price: '£299.99',
    originalPrice: '£399.99',
    features: [
      'Sponsor compliance monitoring',
      'Comprehensive checking',
      'Risk assessment',
      'Professional assessment reports',
      'Sponsor compliance dashboard',
      'AI monitoring assistant',
      'Report generation and sharing',
      'Compliance management',
      'Risk tracking',
      'Automated alerts'
    ],
    keyBenefits: [
      'Comprehensive monitoring',
      'Risk assessment',
      'Compliance assurance',
      'Professional documentation',
      'Risk alerts'
    ],
    status: 'coming-soon',
    category: 'compliance',
    complexity: 'enterprise',
    href: '/ai-sponsor-compliance',
    popular: false,
    new: false
  },
  {
    id: 'third-party-labour',
    name: 'AI Third Party Labour Agent',
    description: 'Third party labour compliance monitoring and analysis for UK sponsors.',
    icon: 'Users',
    price: '£219.99',
    originalPrice: '£299.99',
    features: [
      'Third party labour monitoring',
      'Compliance checking',
      'Risk assessment',
      'Professional assessment reports',
      'Third party compliance dashboard',
      'AI monitoring assistant',
      'Report generation and sharing',
      'Labour management',
      'Compliance tracking',
      'Risk alerts'
    ],
    keyBenefits: [
      'Automated labour monitoring',
      'Compliance checking',
      'Risk assessment',
      'Professional documentation',
      'Risk alerts'
    ],
    status: 'coming-soon',
    category: 'compliance',
    complexity: 'advanced',
    href: '/ai-third-party-labour-compliance',
    popular: false,
    new: false
  },
  {
    id: 'paragraph-c7-26',
    name: 'AI Paragraph C7.26 Agent',
    description: 'Paragraph C7.26 compliance monitoring and analysis for UK sponsors.',
    icon: 'FileText',
    price: '£189.99',
    originalPrice: '£259.99',
    features: [
      'Paragraph C7.26 monitoring',
      'Compliance checking',
      'Risk assessment',
      'Professional assessment reports',
      'C7.26 compliance dashboard',
      'AI monitoring assistant',
      'Report generation and sharing',
      'Compliance management',
      'Risk tracking',
      'Automated alerts'
    ],
    keyBenefits: [
      'Automated C7.26 monitoring',
      'Compliance checking',
      'Risk assessment',
      'Professional documentation',
      'Risk alerts'
    ],
    status: 'coming-soon',
    category: 'compliance',
    complexity: 'advanced',
    href: '/ai-paragraph-c7-26-compliance',
    popular: false,
    new: false
  },
  {
    id: 'immigration-status',
    name: 'AI Immigration Status Agent',
    description: 'Immigration status monitoring and compliance checking for UK sponsors.',
    icon: 'Globe',
    price: '£239.99',
    originalPrice: '£319.99',
    features: [
      'Immigration status monitoring',
      'Visa compliance checking',
      'Status tracking',
      'Professional assessment reports',
      'Immigration compliance dashboard',
      'AI monitoring assistant',
      'Report generation and sharing',
      'Status management',
      'Compliance tracking',
      'Automated alerts'
    ],
    keyBenefits: [
      'Automated status monitoring',
      'Visa compliance checking',
      'Status tracking',
      'Professional documentation',
      'Automated alerts'
    ],
    status: 'coming-soon',
    category: 'compliance',
    complexity: 'enterprise',
    href: '/ai-immigration-status-monitoring-compliance',
    popular: false,
    new: false
  },
  {
    id: 'migrant-contact',
    name: 'AI Migrant Contact Agent',
    description: 'Migrant contact maintenance and compliance monitoring for UK sponsors.',
    icon: 'MessageSquare',
    price: '£159.99',
    originalPrice: '£229.99',
    features: [
      'Contact maintenance monitoring',
      'Communication tracking',
      'Compliance checking',
      'Professional assessment reports',
      'Contact compliance dashboard',
      'AI monitoring assistant',
      'Report generation and sharing',
      'Contact management',
      'Compliance tracking',
      'Automated reminders'
    ],
    keyBenefits: [
      'Automated contact monitoring',
      'Communication tracking',
      'Compliance checking',
      'Professional documentation',
      'Automated reminders'
    ],
    status: 'coming-soon',
    category: 'hr',
    complexity: 'basic',
    href: '/ai-migrant-contact-maintenance-compliance',
    popular: false,
    new: false
  },
  {
    id: 'migrant-tracking',
    name: 'AI Migrant Tracking Agent',
    description: 'Migrant tracking and compliance monitoring for UK sponsors.',
    icon: 'Target',
    price: '£199.99',
    originalPrice: '£279.99',
    features: [
      'Migrant tracking monitoring',
      'Location tracking',
      'Compliance checking',
      'Professional assessment reports',
      'Tracking compliance dashboard',
      'AI monitoring assistant',
      'Report generation and sharing',
      'Tracking management',
      'Compliance tracking',
      'Automated alerts'
    ],
    keyBenefits: [
      'Automated tracking monitoring',
      'Location tracking',
      'Compliance checking',
      'Professional documentation',
      'Automated alerts'
    ],
    status: 'coming-soon',
    category: 'compliance',
    complexity: 'advanced',
    href: '/ai-migrant-tracking-compliance',
    popular: false,
    new: false
  }
] 