# NextAuth Configuration
NEXTAUTH_URL=http://localhost:3000
NEXTAUTH_URL_INTERNAL=http://localhost:3000
NEXTAUTH_SECRET=your-secret-key-generate-a-long-random-string-here

# Supabase Configuration
NEXT_PUBLIC_SUPABASE_URL=https://ounxkplozusdysevpjan.supabase.co
NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91bnhrcGxvenVzZHlzZXZwamFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNTIyMTMsImV4cCI6MjA2NDYyODIxM30.GrOR19kkRnSkEaMJ4PRAp8G4Tqf5Kg0JspLP_AEi_8M
SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91bnhrcGxvenVzZHlzZXZwamFuIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0OTA1MjIxMywiZXhwIjoyMDY0NjI4MjEzfQ.7uxA2gPWAXdG-0-WvUz5EFAxUwf9exuW7jTMmg1iFEg

# Other Configuration (if needed)
NODE_ENV=development



